# Generated by Django 2.0 on 2018-01-02 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data_time', models.DateTimeField()),
                ('Voltaje', models.DecimalField(decimal_places=3, max_digits=7)),
                ('Corriente', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Watts', models.DecimalField(decimal_places=3, max_digits=10)),
                ('VA', models.DecimalField(decimal_places=3, max_digits=10)),
                ('VAR', models.DecimalField(decimal_places=3, max_digits=10)),
                ('FP', models.DecimalField(decimal_places=2, max_digits=3)),
                ('nodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.Nodo')),
            ],
        ),
    ]
