# Generated by Django 2.0 on 2018-01-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodo',
            name='SerialNumber',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
